[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/draft-state"
  to = "/.netlify/functions/draft-state"
  status = 200

[[redirects]]
  from = "/api/manual-odds"
  to = "/.netlify/functions/manual-odds"
  status = 200

[[redirects]]
  from = "/api/pipeline/*"
  to = "/.netlify/functions/pipeline-data"
  status = 200

[[redirects]]
  from = "/api/run-pipeline"
  to = "/.netlify/functions/run-pipeline"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
